### ISSUE TITLE
curious what this provides over ssh -R  (remote port forwarding)

### ISSUE THREAD

**Issue by chug2k** [peterwilli/Ghoster#2]
I'm not very knowledgeable about ssh and tunneling, but 

https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding

talks about how we can use ssh -R.

**Comment by peterwilli** [comment]
Hey @chug2k ! `ssh -R` works only if the client is already running a SSH server. On top of that, if not configured right, it'll give you a SSH shell where you can execute commands in.

Ghoster takes this out of hand, and also isolates the SSH client from the rest of your system by using docker for extra security, making it easier to host as a public service.

Ghoster also assigns the next available port on your system so that you don't have to worry about which ports are available or not.
